routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('ad.index');
});


Route::get('/dashboard', function () {
    return view('dashboard.index');
})->name('dashboard');

Route::resource('ad', 'AdController');
Route::resource('call-taker', 'CallTakerController');

Route::post('/api/v2016/calls/incoming', 'TwilioRestController@incomingCalls');
Route::get('/api/v2016/texts/incoming', 'TwilioRestController@incomingTexts');

Auth::routes();
Route::get('/home', 'HomeController@index');

app/Models/CallTaker.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CallTaker extends Model
{
    Use SoftDeletes;
    
    protected $table = 'call_takers';
    
    protected $guarded = [];
    
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/CallTakerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\CallTaker;

class CallTakerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $takers = CallTaker::all();
        
        return view('call-takers.index', compact('takers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('call-takers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $taker = new CallTaker($request->all());
        $taker->name = $taker->first . ' ' . $taker->last;
        $taker->save();
        
        return redirect()->route('call-taker.show', ['id' => $taker->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $taker = CallTaker::find($id);
        
        return view('call-takers.show', compact('taker'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $taker = CallTaker::find($id);
        
        return view('call-takers.edit', compact('taker'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $taker = CallTaker::find($id);
        $taker->fill($request->all());
        $taker->name = $taker->first . ' ' . $taker->last;
        $taker->save();
        
        return redirect()->route('call-takers.show', compact('id'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        CallTaker::find($id)->delete();
        
        return redirect()->route('call-taker.index');
    }
}

resources/views/call-takers/create.blade.php
@extends('layouts.master')

@section('content')
<h3>Add a Call Taker</h3>
{!! Form::open([
    'url' => route('call-taker.store'), 
    'method' => 'post'
]) !!}
    <div class="form-group">
    {!! Form::label('first', 'First Name: ') !!}
    {!! Form::text('first') !!}
    </div>
    <div class="form-group">
    {!! Form::label('last', 'Last Name: ') !!}
    {!! Form::text('last') !!}
    </div>
    <div class="form-group">
    {!! Form::label('number', 'Phone Number: ') !!}
    {!! Form::text('number') !!}
    </div>
    {!! Form::submit('Add', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/call-takers/edit.blade.php
@extends('layouts.master')

@section('content')
    <h2>Edit a Call Taker </h2>
    {!! Form::model($taker, [
        'route' => ['call-taker.update', $taker->id], 
        'method' => 'put'
    ]) !!}
    <div class="form-group">
        {!! Form::label('first', 'First Name:') !!}
        {!! Form::text('first') !!}
    </div>
    <div class="form-group">
        {!! Form::label('last', 'Last Name:') !!}
        {!! Form::text('last') !!}
    </div>
    <div class="form-group">
        {!! Form::label('number', 'Phone Number:') !!}
        {!! Form::text('number') !!}
    </div>
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    {!! Form::close() !!}
    {!! Form::open(['url' => route('call-taker.destroy', $taker->id),
                'method' => 'DELETE']) !!}
    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
    {!! Form::close() !!}
@stop

resources/views/call-takers/index.blade.php
@extends('layouts.master')

@section('content')    
    <div class="row">
        <div class="col-lg-8">
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>Phone Number</th>
                    <th>
                      <a href="{{ route('call-taker.create') }}" class="btn btn-primary btn-xs">
                        Add
                      </a>
                    </th>
                </thead>
                <tbody>
                    @foreach ($takers as $taker)
                        <tr>
                            <td> {{ $taker->name }} </td>
                            <td> {{ $taker->number }} </td>
                            <td>
                                {!! Html::link(route('call-taker.edit', $taker->id), 'Edit',
                                               ['class' => 'btn btn-default btn-xs']) !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('scripts')
    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js') !!}
    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js')!!}
    <!-- {!! Html::script('/js/pieCharts.js') !!} -->
@stop

resources/views/call-takers/show.blade.php
@extends('layouts.master')

@section('content')
    <h2>{{ $taker->name }}</h3>
    <p>Phone Number: {{ $taker->number }}</p>
    <a href='{{ route('call-taker.edit', ['id' => $taker->id]) }}'>Edit</a>
@stop