routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('ad.index');
});


Route::get('/dashboard', function () {
    return view('dashboard.index');
})->name('dashboard');

Route::resource('ad', 'AdController');
Route::resource('call-taker', 'CallTakerController');

Route::post('/api/v2016/calls/incoming', 'TwilioRestController@incomingCalls');
Route::get('/api/v2016/texts/incoming', 'TwilioRestController@incomingTexts');

Auth::routes();
Route::get('/home', 'HomeController@index');

app/Models/Ad.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\CallTaker;

class Ad extends Model
{
    protected $table = 'ads';
    
    /**
     * $codes => $values of Ad Types.
     * 
     * @var array
     */
    protected static $typeCodes = [
        'fb' => 'Facebook',
        'cl' => 'Craigslist',
        'bs' => 'Bandit Sign',
        'ml' => 'Mail',
        'wb' => 'Website',
    ];
    
    /**
     * Return $codes => $values array of accepted Ad Types. 
     * 
     * @return array
     */
    public static function getTypeCodes()
    {
        return static::$typeCodes;
    }
    
    /**
     * Get Ad's call takers.
     * 
     * @return array 
     */
    public function callTakers()
    {
        return $this->getConnection()->table('call_takers')
                ->join('ad_call_takers', 
                        'ad_call_takers.call_taker_id', '=', 'call_takers.id')
                ->join('ads', 
                        'ad_call_takers.ad_id', '=', 'ads.id')
                ->where('ads.id', '=', $this->id)
                ->whereNull('ad_call_takers.deleted_at')
                ->select('call_takers.*');
    }
    
    /**
     * Get the next person in line to take a call.
     * 
     * @return \App\Models\CallTaker
     */
    public function getNextCallTaker()
    {
        $callTakers = $this->callTakers()->orderBy('id')->get();
        $lastLead = $this->getConnection()->table('leads')
                ->where('initial_ad_id', '=', $this->id)
                ->orderBy('created_at', 'desc')
                ->first();
        
        // First lead of an ad
        if (count($lastLead) < 1)
        {
            return $callTakers[0];
        }
       
        // Find next call taker or circle around array.
        foreach ($callTakers as $key => $taker)
        {
            if ($taker->id == $lastLead->assigned_to)
            {
                break;
            }
        }
        $key = (($key + 2) <= count($callTakers)) ? $key + 1 : 0;
        
        return CallTaker::find($callTakers[$key]->id);
    }
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Ad;
use App\Models\CallTaker;
use App\Models\AdCallTaker;
use Twilio\Rest\Client;
use Illuminate\Support\Facades\View;

class AdController extends Controller
{
    /**
     * @var Twilio\Rest\Client 
     */
    protected $twilio;
    
    public function __construct(Client $twilio)
    {
        $this->twilio = $twilio;
        
        View::share('typeCodes', Ad::getTypeCodes());
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads = Ad::all();
        
        return view('ads.index', compact('ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $takers = CallTaker::all();
        
        return view('ads.create', compact('takers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ad = new Ad;
        $ad->type = $request->get('type');
        $ad->description = $request->get('description');        
        $ad->number = $request->get('number');
        $ad->save();
        
        // Fill in the takers
        foreach ($request->get('takers') as $id)
        {
            $taker = new AdCallTaker;
            $taker->ad_id = $ad->id;
            $taker->call_taker_id = $id;
            $taker->save();
        }
        
        return redirect()->route('ad.show', ['id' => $ad->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ad = Ad::find($id);
        
        return view('ads.show', compact('ad'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ad = Ad::find($id);
        $assignedTakers = $ad->callTakers()->get();
        $avaliableTakers = CallTaker::all();
        
        $takers = [];
        foreach ($avaliableTakers as $avaliableTaker)
        {
            $avaliableTaker->assigned = false; 
            
            foreach ($assignedTakers as $assignedTaker)
            {
                if ($assignedTaker->id == $avaliableTaker->id)
                {
                    $avaliableTaker->assigned = true;
                    break;
                }
            }

            
            $takers[] = $avaliableTaker;
        }
        
        return view('ads.edit', compact('ad', 'takers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ad = Ad::find($id);
        $ad->type = $request->get('type');
        $ad->description = $request->get('description');
        $ad->number = $request->get('number');
        $ad->save();
        
        // Fill in the takers
        $requestTakers = $request->get('takers');
        $currentTakers = $ad->callTakers()->get();
        if (count($requestTakers) !== count($currentTakers))
        {
            // New Takers
            foreach ($requestTakers as $requestTakerId)
            {
                $create = true;
                foreach ($currentTakers as $currentTaker)
                {
                    if ($currentTaker->id == $requestTakerId)
                    {
                        $create = false;
                        break;
                    }
                }

                if ($create)
                {
                    $taker = new AdCallTaker;
                    $taker->ad_id = $ad->id;
                    $taker->call_taker_id = $requestTakerId;
                    $taker->save();
                }
            }

            // Remove Takers
            foreach ($currentTakers as $currentTaker)
            {
                $delete = true;
                foreach ($requestTakers as $requestTakerId)
                {
                    if ($currentTaker->id == $requestTakerId)
                    {
                        $delete = false;
                        break;
                    }
                }

                if ($delete)
                {
                    AdCallTaker::where('ad_id', '=', $ad->id)
                            ->where('call_taker_id', '=', $currentTaker->id)
                            ->delete();
                }
            }
        }
        
        return redirect()->route('ad.show', ['id' => $ad->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ads/create.blade.php
@extends('layouts.master')

@section('content')
<h3>Add an Ad</h3>
{!! Form::open([
    'url' => route('ad.store'), 
    'method' => 'post',
    'files' => true
]) !!}
    <div class="form-group">
    {!! Form::label('type', 'Type: ') !!}
    {!! Form::select('type',$typeCodes) !!}
    </div>
    <div class="form-group">
    {!! Form::label('description', 'Description: ') !!}
    {!! Form::text('description') !!}
    </div>
    <div class="form-group">
    {!! Form::label('number', 'Phone Number: ') !!}
    {!! Form::text('number') !!}
    </div>
    <h4>Call Takers</h4>      
    @foreach ($takers as $taker)
        <div class="form-group">
        {!! Form::label('takers['.$taker->id.']', $taker->name . ':') !!}
        {!! Form::checkbox('takers['.$taker->id.']', $taker->id) !!}
        </div>
    @endforeach
    {!! Form::submit('Add', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/ads/edit.blade.php
@extends('layouts.master')

@section('content')
<h3>Edit an Ad</h3>
{!! Form::model($ad, [
    'route' => ['ad.update', $ad->id], 
    'method' => 'put',
    'files' => true
]) !!}
    <div class="form-group">
    {!! Form::label('type', 'Type: ') !!}
    {!! Form::select('type',$typeCodes) !!}
    </div>
    <div class="form-group">
    {!! Form::label('description', 'Description: ') !!}
    {!! Form::text('description') !!}
    </div>
    <div class="form-group">
    {!! Form::label('number', 'Phone Number: ') !!}
    {!! Form::text('number') !!}
    </div>
    <h4>Call Takers</h4>      
    @foreach ($takers as $taker)
        <div class="form-group">
        {!! Form::label('takers['.$taker->id.']', $taker->name . ':') !!}
        {!! Form::checkbox(
            'takers['.$taker->id.']', 
            $taker->id,
            $taker->assigned
        ) !!}
        </div>
    @endforeach
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/ads/index.blade.php
@extends('layouts.master')

@section('content')    
    <div class="row">
        <div class="col-lg-8">
            <table class="table">
                <thead>
                    <th>Type</th>
                    <th>Phone Number</th>
                    <th>Description</th>
                    <th>Assigned to</th>
                    <th>
                      <a href="{{ route('ad.create') }}" class="btn btn-primary btn-xs">
                        Add
                      </a>
                    </th>
                </thead>
                <tbody>
                    @foreach ($ads as $ad)
                        <tr>
                            <td> {{ $typeCodes[$ad->type] }} </td>
                            <td> {{ $ad->number }} </td>
                            <td> {{ $ad->description }} </td>
                            <td> 
                              @foreach ($ad->callTakers()->get() as $taker)
                              <div class="btn-xs"> {{ $taker->name }} </div>
                              @endforeach
                            </td>
                            <td>
                                {!! Html::link(route('ad.edit', $ad->id), 'Edit',
                                               ['class' => 'btn btn-default btn-xs']) !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('scripts')
    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js') !!}
    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js')!!}
    <!-- {!! Html::script('/js/pieCharts.js') !!} -->
@stop

resources/views/ads/show.blade.php
@extends('layouts.master')

@section('content')
    <p>Type: {{ $typeCodes[$ad->type] }}</p>
    <p>Description: {{ $ad->description }}</p>
    <p>Phone Number: {{ $ad->number }}</p>
    <p>Assigned To:</p>
    <ul>
    @foreach ($ad->callTakers()->get() as $taker)
    <li>{{ $taker->name }}</li>
    @endforeach
    </ul>
    
    <a href='{{ route('ad.edit', ['id' => $ad->id]) }}'>Edit</a>
@stop